server/project/plugins.sbt

This is to fix the bad checksum error when importing in in IntelliJ with fetch SBT code enabled.

add JBoss repository

---

server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala

@yanpom reported this bug in the private repo.

fix mstream bug that was emitting duplicate results

---

server/Jenkinsfile

Created Jenkinsfile containing build pipeline.
The pipeline executes all unit and integration tests (`fullTest` sbt task).

add cmwell jenkins pipeline build file

---

server/cmwell-cons/src/main/scala/DataInitializer.scala
server/cmwell-util/src/main/scala/cmwell/util/http/SimpleHttpClient.scala

to prevent default from always being used

implicit actor system added to SimpleHttpClient API 

---

server/cmwell-util/src/main/scala/cmwell/util/http/SimpleHttpClient.scala

by trying to pick up from provided headers

content-type attribute is optional, and now infered if not provided

---

server/cmwell-docs/cmwell-infodocs/Tutorial.Docker.md

Fixed a few typos on Tutorial.Docker.md, testing the process of fixing online.

Fix a few typos, improve readability

---

server/Jenkinsfile

Jenkinsfile can now be opened within blueocean GUI editor

fix jenkinsfile and blueocean editor

---

server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/security/AuthCache.scala
server/cmwell-ws/app/security/AuthUtils.scala

Some more refactoring is required, as seen to TODOs.
Since it touches too much places, we will do it as a second phase.

Using zCache for UserInfotons

---

server/cmwell-batch/src/pack/logback.xml
server/cmwell-bg/src/pack/logback.xml
server/cmwell-controller/src/pack/logback.xml
server/cmwell-dc/src/pack/logback.xml
server/cmwell-ws/src/pack/cw-logback.xml
server/cmwell-ws/src/pack/logback.xml

This will enable tail -f for the QA (hopefully without noticeable performace hit)

Set immidiate flush of the logs to true

---

server/cmwell-common/src/main/scala/cmwell/common/formats/JsonSerializer.scala
server/cmwell-cons/src/main/scala/ctl.scala
server/cmwell-imp/src/main/scala/cmwell/imp/IMPService.scala
server/cmwell-it/src/it/scala/cmwell/it/APIFunctionalityTests.scala
server/cmwell-it/src/it/scala/cmwell/it/Helpers.scala
server/cmwell-kafka-assigner/src/test/scala/cmwell/kafka/KafkaTopicAssignerTest.scala
server/cmwell-tlog/src/main/scala/cmwell/tlog/TLog.scala
server/cmwell-tracking/src/main/scala/cmwell/tracking/TrackingUtil.scala
server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala
server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/SpHandler.scala

Change them to proper log prints

remove println from code

---

server/cmwell-spa/data/react/scripts/app.jsx
server/cmwell-spa/data/react/scripts/components/Header.jsx
server/cmwell-spa/data/react/scripts/components/Infoton.jsx
server/cmwell-spa/data/react/scripts/components/InfotonsList.jsx
server/cmwell-spa/data/react/scripts/main.js

- Boolean values were not rendered
- "no infotons under this path" message was shown when loading
- Search in current folder if not root - the callback to header was not working
- Searching in a different path than current was causing an exception
- Display Names was not working on root infotons list
- App Loading timeout was incremented

UI Bugfixes

---

server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/BulkScrollHandler.scala

consume will now return also old data with system.indexTime=0

---

server/cmwell-ws/app/controllers/Application.scala

added special treatment for a single filter with Should field operator

---

server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/text/Tokens.scala
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala

better parsing consumer API tokens and support also in from,to|
structure

better support in parsing 'to' parameter

---

server/cmwell-bg/src/main/resources/application.conf
server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala
server/cmwell-bg/src/test/resources/application.conf
server/cmwell-bg/src/test/scala/cmwell/bg/test/BGMergerSpec.scala
server/cmwell-grid/src/main/scala/k/grid/service/ServiceCoordinator.scala
server/cmwell-grid/src/test/scala/k/grid/GridSpec.scala

Modifying Test TimeOut pattern.

Israel parent dups 2

---

server/cmwell-bg/src/main/resources/application.conf
server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala
server/cmwell-bg/src/test/resources/application.conf
server/cmwell-bg/src/test/scala/cmwell/bg/test/BGMergerSpec.scala
server/cmwell-grid/src/main/scala/k/grid/service/ServiceCoordinator.scala
server/cmwell-grid/src/test/scala/k/grid/GridSpec.scala

Additional stability improvements.

Iguana tag

---

server/cmwell-domain/src/main/scala/cmwell/domain/InfotonSerializer.scala

using fileContentCountVerifier rather than checking all zeros

---

server/cmwell-ws/app/controllers/FileInfotonCaching.scala

There were two warnings emitted per each FileInfoton Read:
- `Content-Length header was set manually in the header (LENGTH) but is not the same as actual content length (LENGTH).`
- `Content-Type set both in header (MIME) and attached to entity (MIME), ignoring content type from entity. To remove this warning, use Result.as(...) to set the content type, rather than setting the header manually.`

 Fixed treatContentAsAsset according to Play! recommendations

---

server/project/cmwell-build-plugin/CMWellCommon.scala

Changing version name to Jaguar.

---

server/cmwell-docs/cmwell-infodocs/DevGuide.UsingSPARQLOnCM-WellInfotons.md

Adding supported SPARQL version to docs

---

server/cmwell-cons/src/main/scala/DataInitializer.scala
server/cmwell-it/src/it/scala/cmwell/it/AuthTests.scala

- Also: adding default operation by default to built-in power users

Adding Auth. Tests for Priority Write

---

server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala

This will allow fine tuning the sync.
Adding more than one sync infoton is allowed hence few syncs with several queries can be done.

Allow adding qp to dc sync

---

server/cmwell-ws/app/controllers/Application.scala
server/project/Versions.scala

Tested upgrade locally, and it works flawlessly.

patch version upgrades (cassandra,elasticsearch,play)

---

server/cmwell-util/src/main/scala/cmwell/util/concurrent/package.scala
server/cmwell-ws/app/controllers/LoginHandler.scala
server/cmwell-ws/app/security/httpauth/BasicHttpAuthentication.scala

Better exception handling in LoginHandler

---

server/cmwell-dc/src/main/scala/cmwell/dc/stream/TsvRetriever.scala

It seems that using ConnectionPoolSettings withing the newHostConnectionPool takes the fallback config only from reference.conf and not application.conf
After the configuration changes the config was moved to application.conf.
The solution is to manually take the config.
Fixes #194

DcSync: Properly take the http body size from configuration

---

server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceES.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceOps.scala
server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/ld/util/package.scala
server/cmwell-ws/app/logic/CRUDServiceFS.scala
server/cmwell-ws/app/wsutil/package.scala
server/cmwell-ws/conf/routes

This should help us debug live environments easily

upgraded _cas API and add _es API

---

server/cmwell-it/src/it/scala/cmwell/it/APIValidationTests.scala
server/cmwell-util/src/main/scala/cmwell/util/http/SimpleHttpClient.scala
server/cmwell-ws/app/controllers/InputHandler.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala
server/cmwell-ws/app/ld/util/package.scala

properly return 422 for benign ingests

---

server/cmwell-bg/src/main/resources/reference.conf
server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala
server/cmwell-bg/src/test/scala/cmwell/bg/test/CmwellBGSpec.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala

fixed bug in OW processing where re-processing of already persisted while not indexed yet OWC, was indexed with current:false.
added deleteInfotons method to FTSServiceNew

fixed bug in OW processing where re-processing of already persisted while not indexed yet OWC, was indexed with current:false

---

server/cmwell-spa/data/main/scripts/components/Header.jsx
server/cmwell-spa/data/main/scripts/components/InfotonsList.jsx
server/cmwell-spa/data/main/scripts/components/Types.jsx
server/cmwell-spa/data/main/scripts/utils.jsx

- Only getting all types when expand button clicked.
- Default will have `size=10` **in order to relief Elastic performance**.
Fixes #212 as well.

UI Types Navigation Quickfix

---

server/cmwell-ws/app/controllers/SpHandler.scala

This fixes the issue of false positive error of "Fetching [some path] had no results, this might be a data issue", e.g. with yg of no results.

SpHandler Fix for detecting data issues feature

---

server/cmwell-ws/app/security/AuthCache.scala
server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellCommon.scala

AuthCache: Retring on 404 from CAS

---

server/cmwell-ws/app/security/AuthCache.scala
server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellCommon.scala

just added logs & safer code.
partial work of #197 to accept eagerly

Auth cache retry on 404 with logs

---

server/cmwell-controller/src/main/scala/cmwell/ctrl/checkers/ElasticsearchChecker.scala

fix ES health json parse regression due to the move to Play 2.6

---

server/cmwell-it/src/it/scala/cmwell/it/APIValidationTests.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala

forbid markDelete for sys fields + test

---

server/cmwell-cons/src/main/scala/DataInitializer.scala
server/cmwell-it/src/it/scala/cmwell/it/AuthTests.scala
server/cmwell-util/src/main/scala/cmwell/util/concurrent/SingleElementLazyAsyncCache.scala
server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/BackPressureToggler.scala
server/cmwell-ws/app/controllers/IngestPushback.scala
server/cmwell-ws/app/controllers/InputHandler.scala
server/cmwell-ws/app/controllers/LogLevelHandler.scala
server/cmwell-ws/app/controllers/LoginHandler.scala
server/cmwell-ws/app/controllers/NbgToggler.scala
server/cmwell-ws/app/controllers/OutputHandler.scala
server/cmwell-ws/app/controllers/TrafficHandler.scala
server/cmwell-ws/app/filters/AuthFilter.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala
server/cmwell-ws/app/security/AuthCache.scala
server/cmwell-ws/app/security/AuthConsole.scala
server/cmwell-ws/app/security/AuthUtils.scala
server/cmwell-ws/app/security/Authorization.scala
server/cmwell-ws/app/security/Token.scala
server/cmwell-ws/app/security/httpauth/DigestHttpAuthentication.scala

AuthCache Rewrite

---

Readme.md

* Link to ISWC paper
* Drive home the point that we're not a triple store
* Remove the coming soon for Docker as it's driving me a bit nuts seeing it there.

Updated readme based on ISWC learnings

---

server/cmwell-it/src/it/scala/cmwell/it/APIValidationTests.scala
server/cmwell-it/src/it/scala/cmwell/it/IterationsTests.scala

validation test refactor 

---

server/cmwell-ws/app/controllers/SpHandler.scala

until we have duplicates auto-fixed.

Temporarily disabling data issue detection in _sp

---

server/cmwell-cons/src/main/scala/ComponentConf.scala
server/cmwell-ws/app/security/Authentication.scala
server/cmwell-ws/app/security/Token.scala
server/cmwell-ws/src/pack/application.conf

This fixes #299 and also fixes #237

Allow two Play Secrects

---

server/cmwell-ws/build.sbt
server/cmwell-ws/src/cws/resources/application.conf

_// I wonder why we had the `pack`'s one in the first place..._

Enable sbt ws console

---

docs/ReleaseNotes.Nautilus.November.2017.md

Sorry; found a typo in the displayed Git issue number.

Typo in Git issue no. 279.

---

docs/API.ReturnCodes.md
docs/API.TraversingOutboundAndInboundLinksWithXgAndYg.md
docs/API.Update.DeleteOrReplaceValuesInNamedSubGraph.md

Add notes about 422 error when deleting non-existent sub-graphs.
Remove notes about <,>,<<,>> not being supported for xg/yg.
Add sections about piped expressions for yg/gqp.

Error 422; piped yg/gqp; range parameters supported for xg/yg

---

server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/LoginHandler.scala
server/cmwell-ws/app/filters/AuthFilter.scala
server/cmwell-ws/app/security/AuthCache.scala
server/cmwell-ws/app/security/AuthConsole.scala
server/cmwell-ws/app/security/AuthUtils.scala
server/cmwell-ws/app/security/Authorization.scala
server/cmwell-ws/app/security/EagerAuthCache.scala
server/cmwell-ws/app/security/Token.scala
server/cmwell-ws/app/security/httpauth/DigestHttpAuthentication.scala

* Load eagerly (with a certain delay + retries)
* When falling back to direct read - add retrieved key-value to map.

Rewrite AuthCache as a Map

---

server/cmwell-controller/src/main/scala/cmwell/ctrl/checkers/DcChecker.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceES.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceOps.scala
server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala
server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/logic/CRUDServiceFS.scala

1. add with-history parameter to the sync infoton (default is true)
2. add support for with-history to /proc/dc/someId (default is false)
3. changed the dc monitory to reflect the changes and handle with-history properly

Dc sync of current infotons only without history

---

server/build.sbt
server/cmwell-bg/src/test/scala/cmwell/bg/test/CmwellBGSpec.scala
server/cmwell-cons/src/main/scala/DataInitializer.scala
server/cmwell-data-tools-app/src/main/resources/logback.xml
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/ConsumerStatsActor.scala
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/Downloader.scala
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/ArgsManipulations.scala
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/logging/DataToolsLogging.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/Main.scala
server/cmwell-dc/src/pack/logback.xml
server/cmwell-it/src/it/scala/cmwell/it/Helpers.scala
server/cmwell-it/src/it/scala/cmwell/it/TrackingTests.scala
server/cmwell-sparql-agent/build.sbt
server/cmwell-sparql-agent/src/main/resources/reference.conf
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/InfotonReporter.scala
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManagerSettings.scala
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/StpUtil.scala
server/cmwell-util/src/main/scala/cmwell/util/concurrent/package.scala
server/cmwell-ws/app/security/EagerAuthCache.scala
server/cmwell-zstore/src/main/scala/cmwell/zcache/ZCache.scala

1. The STP manager state machine was rewritten
2. fixed the AskTimeoutException when getting elements from BufferFillerActor
3. fix the tools red log
4. use actor's vars only from within the actor context

DataTools: A complete rewrite of the STP mangager

---

server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellBuild.scala
server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellCommon.scala

if user provides a build from sources function
related to #327

enabling recovering a failed fetching of kafka & zookeeper

---

docs/API.Auth.ChangePassword.md
docs/DevGuide.ManagingUsers.md
docs/ReleaseNotes.Nautilus.November.2017.md
docs/ReleaseNotes.Octopus.December.2017.md
docs/ReleaseNotes.TOC.md
docs/Tools.UsingTheSPARQLTriggerProcessor.md

Changes to SPT configuration.
Fix link in Managing Users.
Fix description in Change Password (need user access token, not admin token).

Octopus release notes, changes to STP, some bug fixes.

---

server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/BulkScrollHandler.scala

exposing "parallelism" query parameter for sstream & bulk-consume

---

server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala

Exposing use_auth in /proc/node

---

server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala
server/cmwell-ws/app/actions/DashBoard.scala
server/cmwell-ws/app/logic/CRUDServiceFS.scala

preventing redundant guice injection failures due to TLog errors

defering TLog instantiation (lazy) 

---

server/cmwell-rts/src/main/scala/cmwell/rts/Subscriber.scala
server/cmwell-ws/app/actions/RequestMonitor.scala
server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/IteratorIdDispatcher.scala

Keeping iterator actor until it is safe to dispose it

---

docs/API.Update.AddInfotonsAndFields.md
docs/DevGuide.CallingJavaScalaFunctionsFromSPARQLQueries.md
docs/Intro.CM-WellDataParadigms.md
docs/Tools.UsingTheCM-WellSparkConnector.md
docs/Tools.UsingTheSPARQLTriggerProcessor.md

Fix SPARQL Triggered Processor code example.
Fix navigation links in DataParadigms file.
In AddInfotonsAndFields, add a link to the Formats page.
Change Scala version to 2.12 in a couple of places (still more needed).

Mostly corrections of bugs found by QA.

---

server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala

1. handle removing STP manager infoton when the job is failed of paused
2. fix O(n^2) when reading the infoton list from the user
Fixes #333
Fixes #334

STP manager: remove paused and failed jobs from the list+performance

---

server/Jenkinsfile
server/build.sbt
server/cmwell-batch/build.sbt
server/cmwell-bg/build.sbt
server/cmwell-common/build.sbt
server/cmwell-cons/build.sbt
server/cmwell-controller/build.sbt
server/cmwell-data-tools-app/build.sbt
server/cmwell-dc/build.sbt
server/cmwell-it/build.sbt
server/cmwell-rts/build.sbt
server/cmwell-stortill/build.sbt
server/cmwell-tlog/build.sbt
server/cmwell-ws/build.sbt
server/project/build.properties
server/project/build.sbt
server/project/cmwell-build-plugin/build.sbt
server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellBuild.scala
server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellCommon.scala
server/project/plugins.sbt
server/project/project/build.properties
server/project/sbt-cassandra-plugin/build.sbt
server/project/sbt-cassandra-plugin/src/main/scala/com/github/hochgi/sbt/cassandra/CassandraPlugin.scala
server/project/sbt-kafka-plugin/build.sbt
server/project/sbt-kafka-plugin/src/main/scala/SbtKafkaPlugin.scala
server/project/sbt-zookeeper-plugin/build.sbt
server/project/sbt-zookeeper-plugin/src/main/scala/SbtZookeeperPlugin.scala

Cmwell 216 sbt 1.0.x upgrade

---

docs/API.Stream.CreateIterator.md
docs/API.Stream.GetNextChunk.md

Update docs according to #363

---

server/cmwell-bg/src/main/scala/cmwell/bg/BGMessage.scala
server/cmwell-bg/src/main/scala/cmwell/bg/Runner.scala
server/cmwell-irw/src/main/scala/cmwell/irw/IRWService.scala
server/cmwell-irw/src/main/scala/cmwell/irw/IRWServiceNativeImpl2.scala
server/cmwell-util/src/main/scala/cmwell/util/concurrent/SimpleScheduler.scala

This should resolve the first phase of #421

enlarging cas timeouts to 120 seconds in bg 

---

server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala

Changed bulk consume to false in STP agent

---

server/cmwell-dc/src/main/resources/reference.conf
server/cmwell-dc/src/main/scala/cmwell/dc/Settings.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/TsvRetriever.scala

Also fixes #384 (add 2 retries to bulk-consume)

remove the slow bulk state from the dcSync agent

---

server/cmwell-irw/src/main/scala/cmwell/irw/IRWServiceNativeImpl2.scala

will now show sys fields… will help debug if we know more…)

improving failed batch statements failure messages 

---

server/cmwell-cons/src/main/resources/application.conf
server/cmwell-cons/src/main/resources/logback.xml

This will solve the issue of the logs printing to stdout when using the cons.

adding configuration files for cons (application, logback)

---

server/cmwell-dc/src/main/scala/cmwell/dc/stream/TsvRetriever.scala

adding log print when starting to get the TSVs

---

server/cmwell-bg/src/pack/application.conf
server/cmwell-bg/src/test/resources/application.conf
server/cmwell-fts/src/main/resources/reference.conf
server/cmwell-ws/src/pack/application.conf
server/cmwell-ws/src/pack/cw-application.conf

Setting clusterSniffing=true in all ES clients (ws,cw,bg)

---

server/cmwell-data-tools-app/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessorMain.scala
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessor.scala
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala

This may conflict with #480 as I have changed the Config case class in both fixes.. Need to make sure both merge properly...

#453 Added force option to STP agent config

---

server/cmwell-cons/src/main/scala/DataInitializer.scala
server/cmwell-it/src/it/scala/cmwell/it/NSBackwardCompTests.scala
server/cmwell-ws/app/Global.scala
server/cmwell-ws/app/Settings.scala
server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/InputHandler.scala
server/cmwell-ws/app/ld/cmw/PassiveFieldTypesCache.scala
server/cmwell-ws/app/ld/exceptions/ParsingException.scala
server/cmwell-ws/app/wsutil/RawFieldFilter.scala
server/cmwell-ws/app/wsutil/package.scala

+ _types-cache as valid json to help debug with jq

implementation for #491 #492 #494 

---

server/cmwell-bg/src/test/scala/cmwell/bg/test/BGSequentialSpec.scala
server/cmwell-bg/src/test/scala/cmwell/bg/test/CmwellBGSpec.scala
server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceES.scala
server/cmwell-ws/app/controllers/BulkScrollHandler.scala
server/cmwell-ws/app/ld/cmw/CMWellRDFHelper.scala
server/cmwell-ws/app/ld/cmw/TimeBasedAccumulatedNamespacesCache.scala

+ pagination of 512 sized chunks + fixed /proc/* formatting errors + …

added sortParams in ns cache

---

server/cmwell-ws/app/Global.scala
server/cmwell-ws/app/ld/cmw/TimeBasedAccumulatedNamespacesCache.scala

+ guard blacklists by dumping oldest entries + guard future lists by returning 503 when size cap is reached

eagerly fill ns cache

---

server/cmwell-util/src/main/scala/cmwell/util/collections/package.scala
server/cmwell-util/src/test/scala/cmwell/util/collections/test/SpanWithTests.scala
server/cmwell-ws/app/ld/cmw/TimeBasedAccumulatedNamespacesCache.scala

And allowing partial success to be processed up to first failure

improving error messages given by ns-cache

---

server/cmwell-ws/app/controllers/Application.scala

It is a heavy request and that didn't have any benefit (the limit was too high anyway)

remove context check in stream

---

server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/ld/cmw/CMWellRDFHelper.scala
server/cmwell-ws/app/ld/cmw/TimeBasedAccumulatedNamespacesCache.scala

API:
/_ns-cache?invalidate=ID
/_ns-cache?invalidate-all

cmwell #521 - adding invalidation to ns-cache.

---

server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceES.scala
server/cmwell-it/src/it/scala/cmwell/it/ExpansionTests.scala

and tests to cover it.
fixes #529

using the unmangled field name in ws in-memory filtering (xg/yg/gqp)

---

server/cmwell-ws/app/controllers/Application.scala

Fix #524 - Protecting ns-cache invalidations

---

server/cmwell-it/src/it/scala/cmwell/it/NSBackwardCompTests.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala

Cmwell 538

---

docs/DevGuide.ManagingUsers.md

Add documentation of operations field in user file infotons

---

server/cmwell-common/src/main/scala/cmwell/common/formats/JsonSerializer6.scala
server/cmwell-it/src/it/scala/cmwell/it/RDFTests.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala
server/cmwell-ws/app/wsutil/package.scala

1 - commands parser failed with ArrayIndexOutOfBoundsException
2 - LDFormatParser unlabeled datatypes were converted to CWD URI with type

user defined datatypes bugfixes:

---

server/cmwell-ws/app/controllers/InputHandler.scala
server/cmwell-ws/app/ld/util/package.scala

fixes #565 - same lastModified from infoton generated in same ingest 

---

server/cmwell-it/src/it/scala/cmwell/it/APIFunctionalityTests.scala
server/cmwell-util/src/main/scala/cmwell/util/concurrent/package.scala
server/cmwell-ws/app/wsutil/RawFieldFilter.scala
server/cmwell-ws/app/wsutil/package.scala

to silently pass w/o failing the request.

allowing non existing fields mask

---

server/cmwell-it/src/it/scala/cmwell/it/APIFunctionalityTests.scala
server/cmwell-it/src/it/scala/cmwell/it/APIValidationTests.scala
server/cmwell-it/src/it/scala/cmwell/it/ClientsCompatabilityTests.scala
server/cmwell-it/src/it/scala/cmwell/it/ExpansionTests.scala
server/cmwell-it/src/it/scala/cmwell/it/Helpers.scala
server/cmwell-it/src/it/scala/cmwell/it/ManglingTests.scala
server/cmwell-it/src/it/scala/cmwell/it/NSBackwardCompTests.scala
server/cmwell-it/src/it/scala/cmwell/it/OWTests.scala
server/cmwell-it/src/it/scala/cmwell/it/QuadTests.scala
server/cmwell-it/src/it/scala/cmwell/it/RDFTests.scala
server/cmwell-it/src/it/scala/cmwell/it/SearchTests.scala
server/cmwell-it/src/it/scala/cmwell/it/TrackingTests.scala
server/cmwell-ws/app/controllers/InputHandler.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala

(RDF only, not jsonw) in response body. fixes #574

Repoting every side effect caused by an _in (or _ow) ingest

---

server/build.sbt
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/StpUtil.scala
server/project/build.sbt

And fixing an STP minor compilation error due to merging logically conflicting branches not detected by git as conflict

upgrading scala to 2.12.5 

---

server/cmwell-data-tools-app/src/main/resources/logback.xml
server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/logging/DataToolsLogging.scala
server/cmwell-dc/src/pack/logback.xml

Enabled bad data logging for STP agent in line with bad data logging for data tools app

Enabled Bad data logging for STP agent

---

server/project/build.properties

release notes: https://developer.lightbend.com/blog/2018-04-09-sbt-1-1-4-hotfix

sbt version update

---

docs/examples/iterate/iterate.sh

It shows how to consume infotons using the iterator API.
The script requires [jq](https://stedolan.github.io/jq) to be installed.

Added an iterator example in bash

---

server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/Retry.scala

Added logging in Retry.scala for failed HTTP requests

---

server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
server/cmwell-bg/src/main/scala/cmwell/bg/Runner.scala

Not using Preferred BgActor but 3 possible (adjacent) hosts

---

server/cmwell-common/src/main/scala/cmwell/common/formats/AbstractJsonSerializer.scala
server/cmwell-it/src/it/scala/cmwell/it/SearchTests.scala
server/cmwell-ws/app/wsutil/RawFieldFilter.scala

Fixing _all (it's about time)

---

server/cmwell-ws/app/controllers/InputHandler.scala

https://github.com/thomsonreuters/CM-Well/issues/695

Disable validation of dataCenter value for _ow API

---

server/cmwell-cons/app/cmw.env
server/cmwell-cons/src/main/scala/ctl.scala
server/cmwell-ws/app/controllers/Health.scala

Add export to java home - needed in AWS env

---

server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala

Log HttpResponse if there is a Http error retrieving infotons

---

server/cmwell-ws/app/Settings.scala
server/cmwell-ws/app/controllers/BackPressureToggler.scala
server/cmwell-ws/app/controllers/IngestPushback.scala
server/cmwell-ws/src/pack/application.conf
server/cmwell-ws/src/pack/cw-application.conf

Change backpressure modes names

---

server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerRatePrinter.scala
server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerStream.scala

Fix crawler hang

---

server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerStream.scala

crawler: ignore old bad previous version

---

server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/InfotonReporter.scala

Note - STP will never read this. Is only for test/debug

Save decoded token information to zstore - ticket #719

---

docs/Admin.Backpressure.md
docs/Admin.Kafka.md
docs/Architecture.DCC.md
docs/CM-Well.RootTOC.md
docs/ReleaseNotes.TOC.md
docs/ReleaseNotes.Unicorn.June.2018.md
docs/ReleaseNotes.Viper.June.2018.md

Yaakov, please review carefully, as I made some assumptions and am not 100% sure of my understanding.
Please note especially missing info and questions, indicated by your name.

Viper release notes and related new documentation pages.

---

server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala

Looks like it fixes #767 but there might as well be more reasons, see for one example #771.

Fix duplicates for bg crash

---

docs/Admin.Kafka.md

not hanging the request when consumption is done

modify _kafka docs according to latest change

---

server/cmwell-bg/src/main/scala/cmwell/bg/IndexerStream.scala
server/cmwell-bg/src/main/scala/cmwell/bg/OffsetUtils.scala
server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerStream.scala
server/cmwell-common/src/main/scala/cmwell/common/OffsetsService.scala

offsetService write is now asynchronous

---

server/cmwell-bg/src/main/scala/cmwell/bg/ImpStream.scala

write IndexExisting command to Kafka before writng the IndexNew one

---

server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/Retry.scala

lost in this merge:
https://github.com/thomsonreuters/CM-Well/commit/f966366897f772b96e10c0273929227b3eb8191e#diff-e3aab043a3f445ff9ba6a445bcc50908

Restored gzip decoder wiped out in old merge

---

server/cmwell-bg/src/main/scala/cmwell/bg/CMWellBGActor.scala
server/cmwell-bg/src/main/scala/cmwell/bg/OffsetUtils.scala

check kafka retention offsets when BG loads

---

server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerStream.scala

fix false positive in case future write will be in ES before CAS

---

server/cmwell-bg/src/main/scala/cmwell/bg/Merger.scala
server/cmwell-bg/src/test/scala/cmwell/bg/test/BGMergerSpec.scala
server/cmwell-bg/src/test/scala/cmwell/bg/test/BGResilienceSpec.scala
server/cmwell-bg/src/test/scala/cmwell/bg/test/FailingFTSServiceMockup.scala

Fix false positive detection of the crawler for null update that is written soon after the real one.

Crawler False Positive Fix

---

server/cmwell-cons/src/main/scala/ctl.scala

add header check to WS wait module

---

server/cmwell-bg/src/main/scala/cmwell/crawler/CrawlerStream.scala

crawler: fix delete commands false positive

---

server/cmwell-cons/app/scripts/templates/cassandra-status-viewer-template

cassandra monitor: fix exception in case of DN node with ?

---

server/cmwell-data-tools/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessor.scala

Didn't expect sparql to return empty values :(

Sparqltoroot vars checks for empty result

---

server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala
server/cmwell-ws/app/controllers/BulkScrollHandler.scala

binary search of bulk-consume should honor history now

---

server/cmwell-data-tools/src/main/scala/cmwell/tools/data/ingester/Ingester.scala

Gzip encode _in payload for STP

---

server/cmwell-ws/app/ld/service/WriteService.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala

See issue #956 _// cc @Ivan-Shestakov_

Supporting TRIX format for _in

---

server/cmwell-ws/app/controllers/InputHandler.scala
server/cmwell-ws/app/wsutil/package.scala
server/cmwell-ws/src/pack/logback.xml

disable dripping for _in + add special log file for failed ingests

---

server/cmwell-bg/src/test/resources/application.conf
server/cmwell-formats/src/main/scala/cmwell/formats/RDFFormatter.scala
server/cmwell-formats/src/test/resources/reference.conf
server/cmwell-it/src/it/scala/cmwell/it/HttpsTests.scala

Support HTTPS Output in non-top-level domain

---

server/cmwell-it/src/it/scala/cmwell/it/HttpsTests.scala
server/cmwell-ws/app/ld/util/LDFormatParser.scala

Changing only protocol will not cause WriteCommand

---

server/cmwell-ws/app/controllers/Application.scala

Adding hard limit to length-hint

---

server/cmwell-controller/src/main/scala/cmwell/ctrl/checkers/StpChecker.scala
server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala
server/cmwell-ws/app/actions/SparqlTriggeredProcessorMonitor.scala
server/cmwell-ws/app/controllers/Application.scala

@yanpom - Admin user should now be able to see the controls.
@bryaakov - controls API was accessible to admin users, but the page did not show the links (only to root)

Allow STP controls to admin users

---

server/cmwell-cons/src/main/scala/ctl.scala

This will only affect `.install` and `.upgrade(withSchemaUpdates=true)`, but won't happen in a regular `upgrade.sh` operation. 
Once #776 will be implemented, we can leverage it to add this new topic.

Adding "red_quque" topic to install and upgrade

---

server/project/cmwell-build-plugin/src/main/scala/cmwell/build/CMWellCommon.scala

Release name = Atom

---

server/cmwell-bg/src/pack/application.conf
server/cmwell-fts/src/main/resources/reference.conf
server/cmwell-ws/src/pack/application.conf
server/cmwell-ws/src/pack/cw-application.conf

Delete reference.conf file since most of its content anyway exists on application.conf

Delete reference.conf file

---

server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/InfotonRetriever.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/MessagesTypesAndExceptions.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/Util.scala

Still without support for crashes and restarts. It will be with another PR to keep them small and concrete.

Dc-Sync: add transformations support

---

server/cmwell-cons/src/main/scala/ComponentConf.scala
server/cmwell-cons/src/main/scala/UtilCommands.scala
server/cmwell-cons/src/main/scala/ctl.scala

Also, it fixes a bug that previous CAS check didn't do anything.

add configuration files change check for ES

---

server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/InfotonAllMachinesDistributerAndIngester.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/InfotonRetriever.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/MessagesTypesAndExceptions.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/RatePrinter.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/SingleMachineInfotonIngester.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/TsvRetriever.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/TsvRetrieverFromFile.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/Util.scala

relates to #1125
Still doesn't solve the monitor issue that should monitor the transformed qp

Dc-sync: check the manager key to support transformations and location

---

server/cmwell-ws/app/BGMonitorActor.scala

Fix BG Monitor Actor

---

server/cmwell-it/src/it/scala/cmwell/it/ConsumeTests.scala
server/cmwell-ws/app/controllers/Application.scala

Add fields masking support to Consume API

---

server/cmwell-ws/app/controllers/Application.scala
server/cmwell-ws/app/controllers/IteratorIdDispatcher.scala
server/cmwell-ws/app/logic/CRUDServiceFS.scala

The first call to getChunk does not retrieve any data

Next Chunk Doesnt Contain Data

---

server/cmwell-ws/app/controllers/Application.scala

When changing the code to use fold, should compare to "false"

Fix fold in iterator

---

server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/InfotonRetriever.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/MessagesTypesAndExceptions.scala
server/cmwell-dc/src/main/scala/cmwell/dc/stream/TsvRetriever.scala

Make DC-Sync fill indexTime and LastModifiedBy if not exist

DC-Sync: Fill indexTime and LastModifiedBy

---

server/cmwell-bg/src/test/scala/cmwell/bg/test/CmwellBGSpec.scala

Mandatory to prevent github ci cd from failing

Use spin check instead schedule

---

server/cmwell-cons/src/main/scala/ComponentConf.scala
server/cmwell-cons/src/main/scala/Grid.scala

This flag is not needed anymore since anyway we have only 1 ES

Remove multiple disks flag

---

.gitignore
server/project/plugins.sbt

using https instead of http to eliminate a warning during sbt boot 

---

server/cmwell-fts/src/main/scala/cmwell/fts/FTSService.scala

1. in case of whole bulk exception (properly handle EsRejectedExecutionException)
2. properly handle ProcessClusterEventTimeoutException
3. increase retry count to 30

BG: retry fixes
