- server/cmwell-cons/src/main/scala/ctl.scala
1. rsync fails if the target directory doesn't exist - fixed
2. In case of a system without ~/bin by default in PATH add it to the custom PATH
> Fix sshpass copy and path

- server/cmwell-batch/src/main/scala/cmwell/batch/boot/Runner.scala
The index service is not terminating anymore therefor, no need to log :-)
> No need to log that index service is terminating

- server/cmwell-spa/data/react/css/cmwell.css
- server/cmwell-spa/data/react/scripts/app.jsx
redirecting users to use the old UI for each /proc/* URL,
rather than having the browser stuck.
> Since /proc was not yet implemented in new UI,

- server/cmwell-controller/src/main/scala/cmwell/ctrl/checkers/ZookeeperChecker.scala
without it the client closes the connection before the server's response
> revert zookeeper tcp back to not close connection

- server/cmwell-tlog/build.sbt
Got this error before:
```text
[error] (tlog/*:assembly) deduplicate: different file contents found in the following:
[error] /home/gilad/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-codec/4.0.44.Final/netty-codec-4.0.44.Final.jar:META-INF/io.netty.versions.properties
[error] /home/gilad/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-handler/4.0.44.Final/netty-handler-4.0.44.Final.jar:META-INF/io.netty.versions.properties
[error] /home/gilad/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-buffer/4.0.44.Final/netty-buffer-4.0.44.Final.jar:META-INF/io.netty.versions.properties
[error] /home/gilad/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.0.44.Final/netty-common-4.0.44.Final.jar:META-INF/io.netty.versions.propertie …
```
> tlog tool assembly failed. fixed it by adding merge strategy in build.sbt

- server/cmwell-data-tools-app/src/main/resources/logback.xml
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessor.scala
paths that are detected from sensors are now filtered if they are not
distinct in the specified timed window.
changed data-tools executable log files size and akka log level.
> sparql-triggered-processor paths are not always unique

- server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceES.scala
- server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala
On old indices, there were no indexTime predefined. When first indexTime introduced, it was created in ES with type Int.
This fix tries to use the normal Long type and if it fails, it falls back to Int type.
> Defensive get system.indexTime from ES

- server/cmwell-spa/data/scripts/controllers.js
- which fixes Types navigation that broke becuase of it, as well as other features, such as Format drop-down
> remove ?old-ui query parameter from url, if exists

- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/Downloader.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessor.scala
- server/cmwell-dc/src/pack/logback.xml
- server/cmwell-sparql-agent/src/main/scala/cmwell/tools/data/sparql/SparqlProcessorManager.scala
Dashboard of sparql-triggered-processor now displays data correctly.
The problem was mismatching labels of sparql-triggered-processor components which were reported to the `InfotonReporter` actor.
> Sparql triggered processor dashboard not display data

- server/cmwell-domain/src/main/scala/cmwell/domain/InfotonSerializer.scala
- server/cmwell-domain/src/test/scala/InfotonSerializerSpec.scala
- server/cmwell-it/src/it/scala/cmwell/it/APIValidationTests.scala
We've seen the following warning in logs:
```
WARN content has different length than expected. expected: [...], actual: [...] for uuid [...]
```
But content was valid. also, `ArrayBuilder` does redundant upcasting and downcasting(via `match`) for value types. we can do better, using a regular array directly.
Also added some minor boy-scouting changes while at it.
> optimized file infoton serialization and got rid of wrong warning log

- server/cmwell-data-tools-app/src/main/scala/cmwell/tools/data/downloader/ConsumerMain.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/Downloader.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/japi/DownloaderUtils.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/HeaderOps.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/HttpConnections.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/Retry.scala
- Fix bug in BufferFillerActor in consumer tool. In case of HTTP failure, it will consume the next token after the current retry.
- Remove length argument from consumer tool.
- Add CM-WELL-RT header value to consumer tool logs.
- Change calls to `_out` to use `HTTP.toStrict` in order to set a limit on processing time of HTTP response.
- Add label support in data-tools http connection pool factory.
> Bug fix in consumer tool actor and other minor changes

- server/cmwell-spa/data/main/scripts/domain.jsx
when a displayName is defined for a certain type.rdf but the displayed Infoton of that type has no such field. Rather than showing  an error msg, fallback to path, and add console warning.
Fixes #91
> UI displayName bugfix

- server/cmwell-data-tools-app/src/main/scala/cmwell/tools/data/downloader/ConsumerMain.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/DataPostProcessor.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/Downloader.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/HeaderOps.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/package.scala
- server/cmwell-data-tools/src/test/scala/cmwell/tools/data/downloader/consumer/ConsumerSpec.scala
- server/cmwell-data-tools/src/test/scala/cmwell/tools/data/helpers/BaseWiremockSpec.scala
- server/cmwell-data-tools/src/test/scala/cmwell/tools/data/ingester/IngesterSpec.scala
- server/cmwell-data-tools/src/test/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessorSpec.scala
In case of bulk-consume retry in consumer tool, the tool store  `X-CMWELL-TO` header
in order to send it on retry. This way it should ease the stress on the
server.
ConsumerMain now sends requests to _out only when needed (i.e., does not
send requests to `_out` when format is text or tsv.
> consumer tool optimizations

- server/cmwell-ws/app/logic/CRUDServiceFS.scala
Adding isPriorityQueue to missing method calls, so messages will be Written to the correct queue.
> Adding isPriorityQueue to missing method calls

- server/cmwell-ws/app/controllers/Application.scala
- server/cmwell-ws/app/controllers/BulkScrollHandler.scala
1. Consume can now handle infotons with indexTime=0
2. BulkConsume can now handle more than 1000 infotons that have indexTime equals to the "from" section in the token
> Consume and Bulk Consume: hanlde a case with lots of infotons with the same index time

- server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceES.scala
- server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala
- server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceOps.scala
- server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala
- server/cmwell-ws/app/controllers/Application.scala
- server/cmwell-ws/app/logic/CRUDServiceFS.scala
Adding &qp=... to /proc/dc/someId is now allowed.
This is part of adding dc-sync to ability to sync only part of the data. The virtual infoton is used by the monitor and also in dc itself to check what is the last infoton of the desired query.
> Allow adding qp to virtual dc infotons

- server/cmwell-controller/src/main/scala/cmwell/ctrl/checkers/DcChecker.scala
- server/cmwell-ws/app/actions/ActiveInfotonGenerator.scala
- server/cmwell-ws/app/logic/CRUDServiceFS.scala
1. DcChecker now checks the sync according to the qp
2. /proc/dc/syncName: can now parse the sync alias name from /meta/sys/dc/syncName and show the correct lastIndexTime taking into account also the qp
Fixes #138 and #142
> query parameter support (qp) in dc monitor and ui

- server/cmwell-ws/app/controllers/Application.scala
- server/cmwell-ws/app/wsutil/package.scala
This way an upgrade can be successful even if for some reason the FileInfoton of the SPA Entry Point is not available.
_// Note that 503 is [legit code](https://github.com/thomsonreuters/CM-Well/blob/c3c68aa0aa214fb3debf045350ab14c18f0cad09/server/cmwell-cons/src/main/scala/ctl.scala#L726) in the eyes of cons._
> Using a custom Exception in case when UI is not available.

- server/cmwell-data-tools-app/src/main/scala/cmwell/tools/data/sparql/SparqlTriggeredProcessorMain.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/downloader/consumer/BufferFillerActor.scala
- server/cmwell-data-tools/src/main/scala/cmwell/tools/data/utils/akka/HttpConnections.scala
1. adding logs to STP stand alone to print the reason the stream finished
2. fix the alsoToMat in BufferFillerActor to propagate the stream end to the upstream
3. fix connection pools to not just use the library defaults but also the application.conf values
> STP - adding logs+flow fixes+config fix (second try)

- server/cmwell-ws/app/security/AuthCache.scala
- In case when Search Future will be failing this will work as it is today. But in case it will only return after 10000 millis (i.e. fts timeout), well, current implementation won't fallback to direct read. Added `timeoutFuture` to address this issue.
- Fix #276 with a simple `Try` wrapped `Json.parse` and added relevant log msgs.
> Authcache GraceDeg fix

- server/build.sbt
- server/project/build.properties
- server/project/build.sbt
- server/project/project/build.properties
scala released a new patch for all supported minor versions:
http://scala-lang.org/news/security-update-nov17.html
TL;DR:
security update. vulnerability is exposed when fsc is used, or when running scala scripts.
Since cmwell-cons runs such scripts during deployment, we are affected.
> sbt and scala patch upgrades

- server/cmwell-util/src/main/scala/cmwell/util/http/SimpleHttpClient.scala
Which causes akka's UriParser to fail: https://github.com/akka/akka-http/issues/1547 
This commit fixes #309
> explicitly adding HTTP scheme when no scheme provided, but port is

- server/cmwell-dc/src/main/scala/cmwell/dc/stream/DataCenterSyncManager.scala
- server/cmwell-dc/src/main/scala/cmwell/dc/stream/InfotonRetriever.scala
- server/cmwell-dc/src/main/scala/cmwell/dc/stream/MessagesTypesAndExceptions.scala
- server/cmwell-ws/app/logic/CRUDServiceFS.scala
1. Remove the error printed when TSV retrieve failed. It's only a warning and can be retried.
2. Check that the index time from ES and from CAS match. If not ignore this infoton and write it to the red log.
3. Add the relevant with-history field for the dc virtual infotons in /proc/dc.
4. remove the full stack trace in log print for missing uuid exception
> Dc-Sync: ignore infotons with a faulty index time in CAS

- server/cmwell-common/src/main/scala/cmwell/common/formats/AbstractJsonSerializer.scala
converting dots to underscore to safe guard from ES unintended nesting.
change was checked locally using:
```
$ curl localhost:9000/_in?format=ntriples -H "X-CM-WELL-TOKEN: ... " --data-binary '<http://some.made/up/domain> <http://and.made.up/field#with.dots> "and value" .'
{"success":true}
$ curl -s localhost:9000/proc/fields?format=json | jq -r '.fields.fields[]' | grep -E 'with(_|.)dots'
with_dots.eadC6A:string
$ curl -s 'localhost:9000/?op=search&recursive&qp=with.dots.$eadC6A:&format=json' | jq '[.results.total,.results.infotons[0].system.path]'
[
1,
"/some.made/up/domain"
]
$ curl -s 'localhost:9000/?op=search&recursive&qp=with_dots.$eadC6A:&format=json' | jq '[.results.total,.results.infotons[0].system.path]'
[
1,
"/some.made/up/domain"
]
```
> "ironing" dots to underscore

- server/cmwell-cons/app/scripts/pe/cassandra.yaml
- server/cmwell-cons/app/scripts/templates/cassandra.yaml
- server/cmwell-irw/src/main/scala/cmwell/irw/IRWServiceNativeImpl2.scala
This changes the Cassandra configuration to avoid these log messages. I also added some comments to this area of the code, and remove a line of code that wasn't needed.
> Attempt to suppress C* warning about un-logged batch buffer size.

- server/project/plugins.sbt
Fixes #381
The data-tools-app.jar won't be in the server artifacts and logback.xml won't collide.
> upgrade sbt/pack to fix the data-tools-app jar inside server artifacts

- server/cmwell-controller/src/main/scala/cmwell/ctrl/checkers/DcChecker.scala
In case there was no sync in the sytem the type field won't exit.
It will solve the field not found exception in the logs every 30 seconds
> remove the type check in DcChecker

- server/cmwell-common/src/main/scala/cmwell/common/formats/JsonSerializer.scala
- server/cmwell-fts/src/main/scala/cmwell/fts/FTSServiceNew.scala
- server/cmwell-grid/src/main/scala/k/grid/service/LocalServiceManager.scala
- server/cmwell-it/src/it/scala/cmwell/it/APIFunctionalityTests.scala
- server/cmwell-it/src/it/scala/cmwell/it/ClientsCompatabilityTests.scala
- server/cmwell-it/src/it/scala/cmwell/it/IterationsTests.scala
- server/cmwell-it/src/it/scala/cmwell/it/NSBackwardCompTests.scala
- server/cmwell-util/src/main/scala/cmwell/util/cache/TimeBasedAccumulatedCache.scala
- server/cmwell-ws/app/Global.scala
- server/cmwell-ws/app/controllers/Application.scala
- server/cmwell-ws/app/controllers/IngestPushback.scala
- server/cmwell-ws/app/filters/GeneralAttributesFilter.scala
- server/cmwell-ws/app/ld/cmw/CMWellRDFHelper.scala
- server/cmwell-ws/app/ld/cmw/PassiveFieldTypesCache.scala
- server/cmwell-ws/app/ld/util/LDFormatParser.scala
- server/cmwell-ws/app/logic/CRUDServiceFS.scala
- server/cmwell-ws/app/security/EagerAuthCache.scala
- server/cmwell-ws/app/wsutil/RawFieldFilter.scala
- server/cmwell-ws/app/wsutil/package.scala
- /meta writes will now be ingested to priority queue prior to regular writes
- validating ns infotons before caching
- adjusted tests
- added a time based accumulating caching solution
- nn fields ingested to _in will refuse to accept dots in field name from now on
- auxilary caches are derived directly from main structure
- (potentialy) malicious `qp` queries will be returned with 424 error code and with delay completing request time to 9.5 seconds, giving that requested completed in under 9 seconds.
> 422 error code removal.

- server/cmwell-bg/src/main/scala/cmwell/bg/IndexerStream.scala
It solves a bug that in case of a mixed priority and non priority writes there will be no proper offset updats.
> properly save all the offsets in indexer and not just the max one

- server/cmwell-irw/src/main/scala/cmwell/irw/IRWServiceNativeImpl2.scala
properly fallback to quorum in case reading with consistency level of one returns empty result
> proper fallback to QUORUM

- tools/dataConsistencyTool/cmwell-spark-analysis/src/scripts/internal-consistency.sh
- tools/dataConsistencyTool/cmwell-spark-analysis/src/test/scala/cmwell/analytics/util/TestDiscoverEsTopology.scala
- tools/dataConsistencyTool/extract-index-from-es/src/main/resources/application.conf
- tools/dataConsistencyTool/extract-index-from-es/src/main/scala/cmwell/analytics/downloader/PartitionedDownloader.scala
- tools/dataConsistencyTool/extract-index-from-es/src/scripts/dump-system-fields-from-es.sh
Disables source filtering in `dump-system-fields-from-es.sh` to address issue (500 internal server error) with source-filter-included queries against troubled Elastic indexes. Increases `max-read-attempts` to allow more retries of failed shard downloads. Modifies `PartitionedDownlaoader` to specify more information in logs and to pause between download request retries when a request fails. Modifies `TestDiscoverEsTopology`, labeling the test intent and ignoring that intent as the test was not being ignored locally with `@Ignore`.
> Resolves 429 Too Many Requests

- server/cmwell-cons/src/main/scala/ComponentConf.scala
resolve #850 
The requirement is to set a number of shards only on new installations while in upgrade process we should not change it.
1. On a fresh install -> number of shards is equal to Min(#nodes, 10)
2. On upgrade with Elastic restart -> number of shards was not changed
3. On upgrade without Elastic restart -> number of shards was not changed
Scenarios 1-3 were tested on both PE and cluster
> Set number of shards

- server/build.sbt
- server/cmwell-cons/build.sbt
Fix include 3 parts: 
1. packCons will refer to *cons* and not to controller so that semverfi will be included
2. before date we will have - and not + for versioning correctness
3. Adding dependency for semverfi
> Support versioning in build.sbt

- server/cmwell-ws/app/controllers/InputHandler.scala
- server/cmwell-ws/src/pack/application.conf
We have a use case of a customer who needs to use _replaceGraph_ API for a large graph (payload in NQuads format is  about 314MB); current implementation of user is to break down the post. Doing so can cause data inconsistency, as the new graph should be contained entirely in same POST as the replaceGraph command.
We will ask them to post the entire graph when replacing it, but first we need to increase our limitation.
- Eli && Liel, I'd like both of you to review this one. Thanks.
- Let's think about WS's memory, and the amount of free space in `/tmp`.
> Increasing payload limit for _in

- server/cmwell-ws/app/wsutil/RawFieldFilter.scala
It was needed for dc-sync with qp to allow filtering only subpath that is not from root.
relates to #1136
> allow :: operator for system.parent.parent_hierarchy

- server/cmwell-ws/app/ld/util/LDFormatParser.scala
These are common characters in Wikidata URIs - currently CM-Well is unable to import Wikidata dumps.
Fixes https://github.com/CM-Well/CM-Well/issues/1121
> Allow percent, comma, and colon in URIs

- server/cmwell-cons/src/main/scala/Grid.scala
When using Grid division, after upgrade, only 1 bg actor would start.
Fixes #1178
> Set correct number of partitions on Grid upgrade

- server/cmwell-ws/app/controllers/Application.scala
- server/cmwell-ws/app/logic/services/ServicesRoutesCache.scala
Having a var immutable map is good enough pattern to get latest stable picture, no need for an internal Actor to sync writes if we schedule a simple method invocation. _// cc @MoriaYechiel_
> Simplfied impl. upon review from Dudi

- server/cmwell-bg/src/main/scala/cmwell/bg/IndexerStream.scala
- server/cmwell-bg/src/pack/application.conf
- server/cmwell-bg/src/pack/logback.xml
- server/cmwell-fts/src/main/scala/cmwell/fts/FTSService.scala
- server/cmwell-ws/app/BGMonitorActor.scala
retry fixes:
1. in case of whole bulk exception
2. in case of new fileds creation timeout in ES
3. current=false was sent to ES before the actual infoton was written
Crawler parallelism increased to 5
BGMonitorActor won't kill BG anymore, just monitor
BG logs rolling increase to 3 weeks
> BG: fix wrong offset reporting in case of fast writes+retry fixes
